# -*- coding: utf-8 -*-
"""NAIVE BAYES TITANIC SURVIVAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RT3WElMTH0ZFLxUZCFRBaJ3ivkZ7pra8

SURVIVAL RATE CALCULATION OF TITANIC PASSENGERS USING NAIVE BAYES
"""

import pandas as pd

df=pd.read_csv("titanic.csv")

print(df.columns)

df.head()

"""HERE I WILL REMOVE THOSE COLUMNS WHICH HAVE NO CONNECTION WITH CALCULATION OF SURVIVAL RATE"""

df.drop(["PassengerId", "Name", "SibSp", "Parch", "Ticket", "Cabin", "Embarked"], axis="columns", inplace=True)
#axis=0 or axis=columns mean the operation will be performed across columns
#inplace=true ,means the changes will be modified in the datafram and the modidfied dataframe will
#be given with changes
#implace=true,means a news data fram with the changes will be given

df.head()

"""NOW THE ENTIRE DATASET IS DIVIDED INTO TWO PARTS

*   inputs-which is used predict the outcome
*   target-which is the outcome that is predicted


"""

target=df.Survived
inputs=df.drop("Survived",axis="columns")

target.head()

inputs.head()

"""THE SEX COLUMN HAS TO BE CHANGED INTO INTEGER TYPES"""

dummies = pd.get_dummies(inputs['Sex'])
dummies = dummies.astype(int)

dummies.head(3)

"""NOW THE COLUMN OF SEX WITH INTEGERS HAS TO BE ADDED BACK TO THE INPUTS"""

inputs=pd.concat([inputs,dummies],axis="columns")
inputs.head(3)

"""SINCE THE GENDER HAS BEEN CHANGED INTO BINARY VALUES THEN THE GENDER COLUMN WITH MALE AND FEMALE VALUES HAS TO BE REMOVED"""

inputs.drop("Sex",axis="columns",inplace=True)

inputs.head()

"""HERE WE WANT TO CHECK IF THERE ARE ANY COLUMNS WITH NA VALUES"""

inputs.columns[inputs.isna().any()]

inputs.Age[:10]

"""NOW WE HAVE TO REPLACE THE NA VALUE WITH THE MEAN VALUE OF THE ENTIRE COLUMN"""

inputs.Age=inputs.Age.fillna(inputs.Age.mean())

inputs.head(6)

"""NOW THE INPUTS ARE DIVIDED INTO TRAINING AND TESTING STATES INTO 80 AND 20 PERCENT RATIO RESPECTIVELY"""

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(inputs,target,test_size=0.2)

len(X_test)

len(X_train)

len(inputs)

"""NOW MODEL IS IMPORTED HERE FOR THE TRAINING AND TESTING PURPOSES"""

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

model.fit(X_train,Y_train)

model.score(X_test,Y_test)

Y_test[:10]

model.predict(X_test[:10])

model.predict_proba(X_test[:10])#in the given below array first part is chance of death and second part
#is chance of survival

